# Analyze significance 
require("proxy")

# Loads annotation times from .txt file that was generated by learning_effect_significance.py
loadData <- function(src)
{
    maxElmts <- max(count.fields(src, sep = ","));
    # Data is read into a data frame object. We create for each annotator the same number of columns for annotation times.
    # If an annotator labeled < maxElmts tweets, the remaining columns are filled with NA.
    # All read strings (here: only annoIDs), are to be interpreted as chars and not factors (=nominal values)
    myData <- read.table(src, header=F, sep=",", col.names = paste0("V",seq_len(maxElmts)),  stringsAsFactors=FALSE, na.strings=c("NA"))
    
    
    # Replace NaN by NA
    myData[is.na(myData)] <- NA
    # Only delete columns where all values are missing
    myData <- myData[,colSums(is.na(myData)) < nrow(myData)]
    return(myData);
}

# Returns the formatted p-value according to significance and converted into a string
formatP <- function(p)
{
    if (p <= 0.01)
    {
        res = paste(c(p, "**"), collapse = "")
    }
    else if (p < 0.05 && p > 0.01)
    {
        res = paste(c(p, "*"), collapse = "")
    }
    else
    {
        res = paste(c(p, ""), collapse = "")
    }
    
    return(res)   
}

# Parameters: 
# s, m: datasets of groups S and M; 
# out: open file to store the infsci2017_results;
# n: max number for firstk and lastk annotation times to consider per annotator
intraGroupSignificance <- function(s, m, out, n)
{
    set.seed(42);
    # k=1 makes no sense here because then all annotation times are used
    for(k in 2:n)
    {
        # Get firstk and lastk annotation times per annotator per group
        firstkS = s[head(seq_along(s), k)]
        lastkS = s[tail(seq_along(s), k)]
        combinedkS <- s[c(head(seq_along(s), k), tail(seq_along(s), k))];
        # Shuffle medians to make the the samples independent in order to avoid having to control the order of the tweets
        # Shuffle each row randomly; sample() only shuffles the columns once, so all rows shuffle the values in the same way
        # This version here first creates from a mxn list a nxm shuffled version which is transposed
        firstkS = t(apply(firstkS, 1, sample));
        lastkS = t(apply(lastkS, 1, sample));
        combinedkS = t(apply(combinedkS, 1, sample));

        firstkM = m[head(seq_along(m), k)]
        lastkM = m[tail(seq_along(m), k)]
        combinedkM <- m[c(head(seq_along(m), k), tail(seq_along(m), k))];
        # Shuffle medians to make the the samples independent in order to avoid having to control the order of the tweets
        # Shuffle each row randomly; sample() only shuffles the columns once, so all rows shuffle the values in the same way
        # This version here first creates from a mxn list a nxm shuffled version which is transposed
        firstkM = t(apply(firstkM, 1, sample));
        lastkM = t(apply(lastkM, 1, sample));
        combinedkM = t(apply(combinedkM, 1, sample));
        
        # Compute medians
        firstk_mediansS <- apply(firstkS, 1, median);
        lastk_mediansS <- apply(lastkS, 1, median);
        combinedk_mediansS <- apply(combinedkS, 1, median);
        
        firstk_mediansM <- apply(firstkM, 1, median);
        lastk_mediansM <- apply(lastkM, 1, median);
        combinedk_mediansM <- apply(combinedkM, 1, median);
        
        # Compute the median of the medians
        first_medianS <- median(firstk_mediansS);
        last_medianS <- median(lastk_mediansS);
        combined_medianS <- median(combinedk_mediansS);
        
        first_medianM <- median(firstk_mediansM);
        last_medianM <- median(lastk_mediansM);
        combined_medianM <- median(combinedk_mediansM);

        # Note: correct=T is mannWhitneyU in Python: scipy-user.10969.n7.nabble.com/stats-ranksums-vs-stats-mannwhitneyu-td14562.html
        # Computations for S
        # 1.H0
        a = wilcox.test(firstk_mediansS, mu=first_medianS, paired=F, exact=F, alternative="two.sided", correct=T);
        b = wilcox.test(firstk_mediansS, mu=first_medianS, paired=F, exact=F, alternative="two.sided", correct=F);
        c = t.test(firstk_mediansS, mu=first_medianS, paired=F, alternative="two.sided", var.equal=F);
        # 2.H0
        d = wilcox.test(lastk_mediansS, mu=last_medianS, paired=F, exact=F, alternative="two.sided", correct=T);
        e = wilcox.test(lastk_mediansS, mu=last_medianS, paired=F, exact=F, alternative="two.sided", correct=F);
        f = t.test(lastk_mediansS, mu=last_medianS, paired=F, alternative="two.sided", var.equal=F);
        # 3.H0
        g = wilcox.test(combinedk_mediansS, mu=combined_medianS, paired=F, exact=F, alternative="two.sided", correct=T);
        h = wilcox.test(combinedk_mediansS, mu=combined_medianS, paired=F, exact=F, alternative="two.sided", correct=F);
        i = t.test(combinedk_mediansS, mu=combined_medianS, paired=F, alternative="two.sided", var.equal=F);
        # 4.H0
        j = wilcox.test(firstk_mediansS, lastk_mediansS, paired=F, exact=F, alternative="two.sided", correct=T);
        l = wilcox.test(firstk_mediansS, lastk_mediansS, paired=F, exact=F, alternative="two.sided", correct=F);
        o = t.test(firstk_mediansS, lastk_mediansS, paired=F, alternative="two.sided", var.equal=F);
        # 5.H0
        p = wilcox.test(firstk_mediansS, combinedk_mediansS, paired=F, exact=F, alternative="two.sided", correct=T);
        q = wilcox.test(firstk_mediansS, combinedk_mediansS, paired=F, exact=F, alternative="two.sided", correct=F);
        r = t.test(firstk_mediansS, combinedk_mediansS, paired=F, alternative="two.sided", var.equal=F);
        # 6.H0
        t = wilcox.test(lastk_mediansS, combinedk_mediansS, paired=F, exact=F, alternative="two.sided", correct=T);
        u = wilcox.test(lastk_mediansS, combinedk_mediansS, paired=F, exact=F, alternative="two.sided", correct=F);
        v = t.test(lastk_mediansS, combinedk_mediansS, paired=F, alternative="two.sided", var.equal=F);
        
        # 4.H0-6.H0 with 1-sample tests
        # 4.H0
        # g = wilcox.test(firstk_mediansS - lastk_mediansS, mu=0, paired=F, exact=F, alternative="two.sided", correct=F);
        # h = t.test(firstk_mediansS - lastk_mediansS, mu=0, paired=F, alternative="two.sided", var.equal=F);
        # # 5.H0
        # i = wilcox.test(firstk_mediansS - combinedk_mediansS, mu=0, paired=F, exact=F, alternative="two.sided", correct=F);
        # j = t.test(firstk_mediansS - combinedk_mediansS, mu=0, paired=F, alternative="two.sided", var.equal=F);
        # # 6.H0
        # l = wilcox.test(lastk_mediansS - combinedk_mediansS, mu=0, paired=F, exact=F, alternative="two.sided", correct=F);
        # o = t.test(lastk_mediansS - combinedk_mediansS, mu=0, paired=F, alternative="two.sided", var.equal=F);
        
        data = c("S", list(k),
                 formatP(a["p.value"]), formatP(b["p.value"]), formatP(c["p.value"]), 
                 formatP(d["p.value"]), formatP(e["p.value"]), formatP(f["p.value"]), 
                 formatP(g["p.value"]), formatP(h["p.value"]), formatP(i["p.value"]), 
                 formatP(j["p.value"]), formatP(l["p.value"]),formatP(o["p.value"]), 
                 formatP(p["p.value"]), formatP(q["p.value"]),formatP(r["p.value"]), 
                 formatP(t["p.value"]), formatP(u["p.value"]), formatP(v["p.value"]));
        write.table(data, file=out, append=T, quote=F, sep=",", col.names=F, row.names=F);

        # Computations for M
        # 1.H0
        a = wilcox.test(firstk_mediansM, mu=first_medianM, paired=F, exact=F, alternative="two.sided", correct=T);
        b = wilcox.test(firstk_mediansM, mu=first_medianM, paired=F, exact=F, alternative="two.sided", correct=F);
        c = t.test(firstk_mediansM, mu=first_medianM, paired=F, alternative="two.sided", var.equal=F);
        # 2.H0
        d = wilcox.test(lastk_mediansM, mu=last_medianM, paired=F, exact=F, alternative="two.sided", correct=T);
        e = wilcox.test(lastk_mediansM, mu=last_medianM, paired=F, exact=F, alternative="two.sided", correct=F);
        f = t.test(lastk_mediansM, mu=last_medianM, paired=F, alternative="two.sided", var.equal=F);
        # 3.H0
        g = wilcox.test(combinedk_mediansM, mu=combined_medianM, paired=F, exact=F, alternative="two.sided", correct=T);
        h = wilcox.test(combinedk_mediansM, mu=combined_medianM, paired=F, exact=F, alternative="two.sided", correct=F);
        i = t.test(combinedk_mediansM, mu=combined_medianM, paired=F, alternative="two.sided", var.equal=F);
        # 4.H0
        j = wilcox.test(firstk_mediansM, lastk_mediansM, paired=F, exact=F, alternative="two.sided", correct=T);
        l = wilcox.test(firstk_mediansM, lastk_mediansM, paired=F, exact=F, alternative="two.sided", correct=F);
        o = t.test(firstk_mediansM, lastk_mediansM, paired=F, alternative="two.sided", var.equal=F);
        # 5.H0
        p = wilcox.test(firstk_mediansM, combinedk_mediansM, paired=F, exact=F, alternative="two.sided", correct=T);
        q = wilcox.test(firstk_mediansM, combinedk_mediansM, paired=F, exact=F, alternative="two.sided", correct=F);
        r = t.test(firstk_mediansM, combinedk_mediansM, paired=F, alternative="two.sided", var.equal=F);
        # 6.H0
        t = wilcox.test(lastk_mediansM, combinedk_mediansM, paired=F, exact=F, alternative="two.sided", correct=T);
        u = wilcox.test(lastk_mediansM, combinedk_mediansM, paired=F, exact=F, alternative="two.sided", correct=F);
        v = t.test(lastk_mediansM, combinedk_mediansM, paired=F, alternative="two.sided", var.equal=F);
        
        # 4.H0-6.H0 with 1-sample tests
        # 4.H0
        # g = wilcox.test(firstk_mediansM - lastk_mediansM, mu=0, paired=F, exact=F, alternative="two.sided", correct=F);
        # h = t.test(firstk_mediansM - lastk_mediansM, mu=0, paired=F, alternative="two.sided", var.equal=F);
        # # 5.H0
        # i = wilcox.test(firstk_mediansM - combinedk_mediansM, mu=0, paired=F, exact=F, alternative="two.sided", correct=F);
        # j = t.test(firstk_mediansM - combinedk_mediansM, mu=0, paired=F, alternative="two.sided", var.equal=F);
        # # 6.H0
        # l = wilcox.test(lastk_mediansM - combinedk_mediansM, mu=0, paired=F, exact=F, alternative="two.sided", correct=F);
        # o = t.test(lastk_mediansM - combinedk_mediansM, mu=0, paired=F, alternative="two.sided", var.equal=F);
        
        data = c("M", list(k),
                 formatP(a["p.value"]), formatP(b["p.value"]), formatP(c["p.value"]), 
                 formatP(d["p.value"]), formatP(e["p.value"]), formatP(f["p.value"]), 
                 formatP(g["p.value"]), formatP(h["p.value"]), formatP(i["p.value"]), 
                 formatP(j["p.value"]), formatP(l["p.value"]),formatP(o["p.value"]), 
                 formatP(p["p.value"]), formatP(q["p.value"]),formatP(r["p.value"]), 
                 formatP(t["p.value"]), formatP(u["p.value"]), formatP(v["p.value"]));
        write.table(data, file=out, append=T, quote=F, sep=",", col.names=F, row.names=F);
    }
}

# Parameters: 
# s: datasets; 
# out: open file to store the infsci2017_results;
# n: max number for firstk and lastk annotation times to consider per annotator
interGroupSignificance <- function(s, out, n)
{
    set.seed(42);
    # k=1 makes no sense here because then all annotation times are used
    for(k in 2:n)
    {
        # Get firstk and lastk annotation times per annotator per group
        firstkS = s[head(seq_along(s), k)]
        lastkS = s[tail(seq_along(s), k)]
        combinedkS <- s[c(head(seq_along(s), k), tail(seq_along(s), k))];
        # Shuffle medians to make the the samples independent in order to avoid having to control the order of the tweets
        # Shuffle each row randomly; sample() only shuffles the columns once, so all rows shuffle the values in the same way
        # This version here first creates from a mxn list a nxm shuffled version which is transposed
        firstkS = t(apply(firstkS, 1, sample));
        lastkS = t(apply(lastkS, 1, sample));
        combinedkS = t(apply(combinedkS, 1, sample));
        
        # Compute medians
        firstk_mediansS <- apply(firstkS, 1, median);
        lastk_mediansS <- apply(lastkS, 1, median);
        combinedk_mediansS <- apply(combinedkS, 1, median);
        
        # Compute the median of the medians
        first_medianS <- median(firstk_mediansS);
        last_medianS <- median(lastk_mediansS);
        combined_medianS <- median(combinedk_mediansS);
        
        # Note: correct=T is mannWhitneyU in Python: scipy-user.10969.n7.nabble.com/stats-ranksums-vs-stats-mannwhitneyu-td14562.html
        # Computations for S
        # 1.H0
        a = wilcox.test(firstk_mediansS, mu=first_medianS, paired=F, exact=F, alternative="two.sided", correct=T);
        b = wilcox.test(firstk_mediansS, mu=first_medianS, paired=F, exact=F, alternative="two.sided", correct=F);
        c = t.test(firstk_mediansS, mu=first_medianS, paired=F, alternative="two.sided", var.equal=F);
        # 2.H0
        d = wilcox.test(lastk_mediansS, mu=last_medianS, paired=F, exact=F, alternative="two.sided", correct=T);
        e = wilcox.test(lastk_mediansS, mu=last_medianS, paired=F, exact=F, alternative="two.sided", correct=F);
        f = t.test(lastk_mediansS, mu=last_medianS, paired=F, alternative="two.sided", var.equal=F);
        # 3.H0
        g = wilcox.test(combinedk_mediansS, mu=combined_medianS, paired=F, exact=F, alternative="two.sided", correct=T);
        h = wilcox.test(combinedk_mediansS, mu=combined_medianS, paired=F, exact=F, alternative="two.sided", correct=F);
        i = t.test(combinedk_mediansS, mu=combined_medianS, paired=F, alternative="two.sided", var.equal=F);
        # 4.H0
        j = wilcox.test(firstk_mediansS, lastk_mediansS, paired=F, exact=F, alternative="two.sided", correct=T);
        l = wilcox.test(firstk_mediansS, lastk_mediansS, paired=F, exact=F, alternative="two.sided", correct=F);
        o = t.test(firstk_mediansS, lastk_mediansS, paired=F, alternative="two.sided", var.equal=F);
        # 5.H0
        p = wilcox.test(firstk_mediansS, combinedk_mediansS, paired=F, exact=F, alternative="two.sided", correct=T);
        q = wilcox.test(firstk_mediansS, combinedk_mediansS, paired=F, exact=F, alternative="two.sided", correct=F);
        r = t.test(firstk_mediansS, combinedk_mediansS, paired=F, alternative="two.sided", var.equal=F);
        # 6.H0
        t = wilcox.test(lastk_mediansS, combinedk_mediansS, paired=F, exact=F, alternative="two.sided", correct=T);
        u = wilcox.test(lastk_mediansS, combinedk_mediansS, paired=F, exact=F, alternative="two.sided", correct=F);
        v = t.test(lastk_mediansS, combinedk_mediansS, paired=F, alternative="two.sided", var.equal=F);
        
        # 4.H0-6.H0 with 1-sample tests
        # 4.H0
        # g = wilcox.test(firstk_mediansS - lastk_mediansS, mu=0, paired=F, exact=F, alternative="two.sided", correct=F);
        # h = t.test(firstk_mediansS - lastk_mediansS, mu=0, paired=F, alternative="two.sided", var.equal=F);
        # # 5.H0
        # i = wilcox.test(firstk_mediansS - combinedk_mediansS, mu=0, paired=F, exact=F, alternative="two.sided", correct=F);
        # j = t.test(firstk_mediansS - combinedk_mediansS, mu=0, paired=F, alternative="two.sided", var.equal=F);
        # # 6.H0
        # l = wilcox.test(lastk_mediansS - combinedk_mediansS, mu=0, paired=F, exact=F, alternative="two.sided", correct=F);
        # o = t.test(lastk_mediansS - combinedk_mediansS, mu=0, paired=F, alternative="two.sided", var.equal=F);
        
        data = c(list(k),
                 formatP(a["p.value"]), formatP(b["p.value"]), formatP(c["p.value"]), 
                 formatP(d["p.value"]), formatP(e["p.value"]), formatP(f["p.value"]), 
                 formatP(g["p.value"]), formatP(h["p.value"]), formatP(i["p.value"]), 
                 formatP(j["p.value"]), formatP(l["p.value"]),formatP(o["p.value"]), 
                 formatP(p["p.value"]), formatP(q["p.value"]),formatP(r["p.value"]), 
                 formatP(t["p.value"]), formatP(u["p.value"]), formatP(v["p.value"]));
        write.table(data, file=out, append=T, quote=F, sep=",", col.names=F, row.names=F);
    }
}

# Parameters: 
# mds, mdm, sus, sum: datasets of groups S and M of MD and SU; 
# dst: open file to store the infsci2017_results;
# n: max number for firstk and lastk annotation times to consider per annotator
interInstGroupSignificance <- function(mds, mdm, sus, sum, dst, n)
{
    set.seed(42);
    # k=1 makes no sense here because then all annotation times are used
    for(k in 2:n)
    {
        # a) Get firstk and lastk annotation times per annotator for MD
        # 1. S
        firstkMDS = mds[head(seq_along(mds), k)];
        lastkMDS = mds[tail(seq_along(mds), k)];
        combinedkMDS <- mds[c(head(seq_along(mds), k), tail(seq_along(mds), k))];
        # 2. M
        firstkMDM = mdm[head(seq_along(mdm), k)];
        lastkMDM = mdm[tail(seq_along(mdm), k)];
        combinedkMDM <- mdm[c(head(seq_along(mdm), k), tail(seq_along(mdm), k))];
        # b) Shuffle medians to make the the samples independent in order to avoid having to control the order of the tweets
        # Shuffle each row randomly; sample() only shuffles the columns once, so all rows shuffle the values in the same way
        # This version here first creates from a mxn list a nxm shuffled version which is transposed
        # 1. S
        firstkMDS = t(apply(firstkMDS, 1, sample));
        lastkMDS = t(apply(lastkMDS, 1, sample));
        combinedkMDS = t(apply(combinedkMDS, 1, sample));
        # 2. M
        firstkMDM = t(apply(firstkMDM, 1, sample));
        lastkMDM = t(apply(lastkMDM, 1, sample));
        combinedkMDM = t(apply(combinedkMDM, 1, sample));
        # c) Compute medians
        # 1. S
        firstk_mediansMDS <- apply(firstkMDS,1, median);
        lastk_mediansMDS <- apply(lastkMDS,1, median);
        combinedk_mediansMDS <- apply(combinedkMDS, 1, median)
        # 2. M
        firstk_mediansMDM <- apply(firstkMDM,1, median);
        lastk_mediansMDM <- apply(lastkMDM,1, median);
        combinedk_mediansMDM <- apply(combinedkMDM, 1, median)
        
        # a) Get firstk and lastk annotation times per annotator for SU
        # 1. S
        firstkSUS = sus[head(seq_along(sus), k)]
        lastkSUS = sus[tail(seq_along(sus), k)]
        combinedkSUS <- sus[c(head(seq_along(sus), k), tail(seq_along(sus), k))];
        # 2. M
        firstkSUM = sum[head(seq_along(sum), k)]
        lastkSUM = sum[tail(seq_along(sum), k)]
        combinedkSUM <- sum[c(head(seq_along(sum), k), tail(seq_along(sum), k))];
        # b) Shuffle medians to make the the samples independent in order to avoid having to control the order of the tweets
        # Shuffle each row randomly; sample() only shuffles the columns once, so all rows shuffle the values in the same way
        # This version here first creates from a mxn list a nxm shuffled version which is transposed
        # 1. S
        firstkSUS = t(apply(firstkSUS, 1, sample));
        lastkSUS = t(apply(lastkSUS, 1, sample));
        combinedkSUS = t(apply(combinedkSUS, 1, sample));
        # 2. M
        firstkSUM = t(apply(firstkSUM, 1, sample));
        lastkSUM = t(apply(lastkSUM, 1, sample));
        combinedkSUM = t(apply(combinedkSUM, 1, sample));
        # c) Compute medians
        # 1. S
        firstk_mediansSUS <- apply(firstkSUS,1, median);
        lastk_mediansSUS <- apply(lastkSUS,1, median);
        combinedk_mediansSUS <- apply(combinedkSUS, 1, median);
        # 2. M
        firstk_mediansSUM <- apply(firstkSUM,1, median);
        lastk_mediansSUM <- apply(lastkSUM,1, median);
        combinedk_mediansSUM <- apply(combinedkSUM, 1, median);
        
        # 1.H0
        aa = wilcox.test(firstk_mediansMDS, firstk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=T);
        ab = wilcox.test(firstk_mediansMDS, firstk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=F);
        ac = t.test(firstk_mediansMDS, firstk_mediansSUS, paired=F, alternative="two.sided", var.equal=F);
        # 2.H0
        ad = wilcox.test(lastk_mediansMDS, firstk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=T);
        ae = wilcox.test(lastk_mediansMDS, firstk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=F);
        af = t.test(lastk_mediansMDS, firstk_mediansSUS, paired=F, alternative="two.sided", var.equal=F);
        # 3.H0
        ag = wilcox.test(combinedk_mediansMDS, firstk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=T);
        ah = wilcox.test(combinedk_mediansMDS, firstk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=F);
        ai = t.test(combinedk_mediansMDS, firstk_mediansSUS, paired=F, alternative="two.sided", var.equal=F);
        # 4.H0
        aj = wilcox.test(firstk_mediansMDS, lastk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=T);
        ak = wilcox.test(firstk_mediansMDS, lastk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=F);
        al = t.test(firstk_mediansMDS, lastk_mediansSUS, paired=F, alternative="two.sided", var.equal=F);
        # 5.H0
        am = wilcox.test(lastk_mediansMDS, lastk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=T);
        an = wilcox.test(lastk_mediansMDS, lastk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=F);
        ao = t.test(lastk_mediansMDS, lastk_mediansSUS, paired=F, alternative="two.sided", var.equal=F);
        # 6.H0
        ap = wilcox.test(combinedk_mediansMDS, lastk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=T);
        aq = wilcox.test(combinedk_mediansMDS, lastk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=F);
        ar = t.test(combinedk_mediansMDS, lastk_mediansSUS, paired=F, alternative="two.sided", var.equal=F);
        # 7.H0
        as = wilcox.test(firstk_mediansMDS, combinedk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=T);
        at = wilcox.test(firstk_mediansMDS, combinedk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=F);
        au = t.test(firstk_mediansMDS, combinedk_mediansSUS, paired=F, alternative="two.sided", var.equal=F);
        # 8.H0
        av = wilcox.test(lastk_mediansMDS, combinedk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=T);
        aw = wilcox.test(lastk_mediansMDS, combinedk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=F);
        ax = t.test(lastk_mediansMDS, combinedk_mediansSUS, paired=F, alternative="two.sided", var.equal=F);
        # 9.H0
        ay = wilcox.test(combinedk_mediansMDS, combinedk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=T);
        az = wilcox.test(combinedk_mediansMDS, combinedk_mediansSUS, paired=F, exact=F, alternative="two.sided", correct=F);
        ba = t.test(combinedk_mediansMDS, combinedk_mediansSUS, paired=F, alternative="two.sided", var.equal=F);

        # 10.H0
        bb = wilcox.test(firstk_mediansMDM, firstk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        bc = wilcox.test(firstk_mediansMDM, firstk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        bd = t.test(firstk_mediansMDM, firstk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        # 11.H0
        be = wilcox.test(lastk_mediansMDM, firstk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        bf = wilcox.test(lastk_mediansMDM, firstk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        bg = t.test(lastk_mediansMDM, firstk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        # 12.H0
        bh = wilcox.test(combinedk_mediansMDM, firstk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        bi = wilcox.test(combinedk_mediansMDM, firstk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        bj = t.test(combinedk_mediansMDM, firstk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        # 13.H0
        bk = wilcox.test(firstk_mediansMDM, lastk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        bl = wilcox.test(firstk_mediansMDM, lastk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        bm = t.test(firstk_mediansMDM, lastk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        # 14.H0
        bn = wilcox.test(lastk_mediansMDM, lastk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        bo = wilcox.test(lastk_mediansMDM, lastk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        bp = t.test(lastk_mediansMDM, lastk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        # 15.H0
        bq = wilcox.test(combinedk_mediansMDM, lastk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        br = wilcox.test(combinedk_mediansMDM, lastk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        bs = t.test(combinedk_mediansMDM, lastk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        # 16.H0
        bt = wilcox.test(firstk_mediansMDM, combinedk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        bu = wilcox.test(firstk_mediansMDM, combinedk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        bv = t.test(firstk_mediansMDM, combinedk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        # 17.H0
        bw = wilcox.test(lastk_mediansMDM, combinedk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        bx = wilcox.test(lastk_mediansMDM, combinedk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        by = t.test(lastk_mediansMDM, combinedk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        # 18.H0
        bz = wilcox.test(combinedk_mediansMDM, combinedk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        ca = wilcox.test(combinedk_mediansMDM, combinedk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        cb = t.test(combinedk_mediansMDM, combinedk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        
        # 19.H0
        cc = wilcox.test(firstk_mediansSUM, firstk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=T);
        cd = wilcox.test(firstk_mediansSUM, firstk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=F);
        ce = t.test(firstk_mediansSUM, firstk_mediansMDS, paired=F, alternative="two.sided", var.equal=F);
        # 20.H0
        cf = wilcox.test(lastk_mediansSUM, firstk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=T);
        cg = wilcox.test(lastk_mediansSUM, firstk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=F);
        ch = t.test(lastk_mediansSUM, firstk_mediansMDS, paired=F, alternative="two.sided", var.equal=F);
        # 21.H0
        ci = wilcox.test(combinedk_mediansSUM, firstk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=T);
        cj = wilcox.test(combinedk_mediansSUM, firstk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=F);
        ck = t.test(combinedk_mediansSUM, firstk_mediansMDS, paired=F, alternative="two.sided", var.equal=F);
        # 22.H0
        cl = wilcox.test(firstk_mediansSUM, lastk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=T);
        cm = wilcox.test(firstk_mediansSUM, lastk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=F);
        cn = t.test(firstk_mediansSUM, lastk_mediansMDS, paired=F, alternative="two.sided", var.equal=F);
        # 23.H0
        co = wilcox.test(lastk_mediansSUM, lastk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=T);
        cp = wilcox.test(lastk_mediansSUM, lastk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=F);
        cq = t.test(lastk_mediansSUM, lastk_mediansMDS, paired=F, alternative="two.sided", var.equal=F);
        # 24.H0
        cr = wilcox.test(combinedk_mediansSUM, lastk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=T);
        cs = wilcox.test(combinedk_mediansSUM, lastk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=F);
        ct = t.test(combinedk_mediansSUM, lastk_mediansMDS, paired=F, alternative="two.sided", var.equal=F);
        # 25.H0
        cu = wilcox.test(firstk_mediansSUM, combinedk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=T);
        cv = wilcox.test(firstk_mediansSUM, combinedk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=F);
        cw = t.test(firstk_mediansSUM, combinedk_mediansMDS, paired=F, alternative="two.sided", var.equal=F);
        # 26.H0
        cx = wilcox.test(lastk_mediansSUM, combinedk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=T);
        cy = wilcox.test(lastk_mediansSUM, combinedk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=F);
        cz = t.test(lastk_mediansSUM, combinedk_mediansMDS, paired=F, alternative="two.sided", var.equal=F);
        # 27.H0
        da = wilcox.test(combinedk_mediansSUM, combinedk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=T);
        db = wilcox.test(combinedk_mediansSUM, combinedk_mediansMDS, paired=F, exact=F, alternative="two.sided", correct=F);
        dc = t.test(combinedk_mediansSUM, combinedk_mediansMDS, paired=F, alternative="two.sided", var.equal=F);
        
        # 28.H0
        dd = wilcox.test(firstk_mediansSUS, firstk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        de = wilcox.test(firstk_mediansSUS, firstk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        df = t.test(firstk_mediansSUS, firstk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 29.H0
        dg = wilcox.test(lastk_mediansSUS, firstk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        dh = wilcox.test(lastk_mediansSUS, firstk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        di = t.test(lastk_mediansSUS, firstk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 30.H0
        dj = wilcox.test(combinedk_mediansSUS, firstk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        dk = wilcox.test(combinedk_mediansSUS, firstk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        dl = t.test(combinedk_mediansSUS, firstk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 31.H0
        dm = wilcox.test(firstk_mediansSUS, lastk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        dn = wilcox.test(firstk_mediansSUS, lastk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        do = t.test(firstk_mediansSUS, lastk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 32.H0
        dp = wilcox.test(lastk_mediansSUS, lastk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        dq = wilcox.test(lastk_mediansSUS, lastk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        dr = t.test(lastk_mediansSUS, lastk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 33.H0
        ds = wilcox.test(combinedk_mediansSUS, lastk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        dt = wilcox.test(combinedk_mediansSUS, lastk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        du = t.test(combinedk_mediansSUS, lastk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 34.H0
        dv = wilcox.test(firstk_mediansSUS, combinedk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        dw = wilcox.test(firstk_mediansSUS, combinedk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        dx = t.test(firstk_mediansSUS, combinedk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 35.H0
        dy = wilcox.test(lastk_mediansSUS, combinedk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        dz = wilcox.test(lastk_mediansSUS, combinedk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        ea = t.test(lastk_mediansSUS, combinedk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 36.H0
        eb = wilcox.test(combinedk_mediansSUS, combinedk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        ec = wilcox.test(combinedk_mediansSUS, combinedk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        ed = t.test(combinedk_mediansSUS, combinedk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        
        # 37.H0
        ee = wilcox.test(firstk_mediansMDS, firstk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        ef = wilcox.test(firstk_mediansMDS, firstk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        eg = t.test(firstk_mediansMDS, firstk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 38.H0
        eh = wilcox.test(lastk_mediansMDS, firstk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        ei = wilcox.test(lastk_mediansMDS, firstk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        ej = t.test(lastk_mediansMDS, firstk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 39.H0
        ek = wilcox.test(combinedk_mediansMDS, firstk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        el = wilcox.test(combinedk_mediansMDS, firstk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        em = t.test(combinedk_mediansMDS, firstk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 40.H0
        en = wilcox.test(firstk_mediansMDS, lastk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        eo = wilcox.test(firstk_mediansMDS, lastk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        ep = t.test(firstk_mediansMDS, lastk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 41.H0
        eq = wilcox.test(lastk_mediansMDS, lastk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        er = wilcox.test(lastk_mediansMDS, lastk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        es = t.test(lastk_mediansMDS, lastk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 42.H0
        et = wilcox.test(combinedk_mediansMDS, lastk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        eu = wilcox.test(combinedk_mediansMDS, lastk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        ev = t.test(combinedk_mediansMDS, lastk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 43.H0
        ew = wilcox.test(firstk_mediansMDS, combinedk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        ex = wilcox.test(firstk_mediansMDS, combinedk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        ey = t.test(firstk_mediansMDS, combinedk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 44.H0
        ez = wilcox.test(lastk_mediansMDS, combinedk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        fa = wilcox.test(lastk_mediansMDS, combinedk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        fb = t.test(lastk_mediansMDS, combinedk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 45.H0
        fc = wilcox.test(combinedk_mediansMDS, combinedk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=T);
        fd = wilcox.test(combinedk_mediansMDS, combinedk_mediansMDM, paired=F, exact=F, alternative="two.sided", correct=F);
        fe = t.test(combinedk_mediansMDS, combinedk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        
        # 46.H0
        ff = wilcox.test(firstk_mediansSUS, firstk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        fg = wilcox.test(firstk_mediansSUS, firstk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        fh = t.test(firstk_mediansSUS, firstk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        # 47.H0
        fi = wilcox.test(lastk_mediansSUS, firstk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        fj = wilcox.test(lastk_mediansSUS, firstk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        fk = t.test(lastk_mediansSUS, firstk_mediansMDM, paired=F, alternative="two.sided", var.equal=F);
        # 48.H0
        fl = wilcox.test(combinedk_mediansSUS, firstk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        fm = wilcox.test(combinedk_mediansSUS, firstk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        fn = t.test(combinedk_mediansSUS, firstk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        # 49.H0
        fo = wilcox.test(firstk_mediansSUS, lastk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        fp = wilcox.test(firstk_mediansSUS, lastk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        fq = t.test(firstk_mediansSUS, lastk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        # 50.H0
        fr = wilcox.test(lastk_mediansSUS, lastk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        fs = wilcox.test(lastk_mediansSUS, lastk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        ft = t.test(lastk_mediansSUS, lastk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        # 51.H0
        fu = wilcox.test(combinedk_mediansSUS, lastk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        fv = wilcox.test(combinedk_mediansSUS, lastk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        fw = t.test(combinedk_mediansSUS, lastk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        # 52.H0
        fx = wilcox.test(firstk_mediansSUS, combinedk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        fy = wilcox.test(firstk_mediansSUS, combinedk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        fz = t.test(firstk_mediansSUS, combinedk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        # 53.H0
        ga = wilcox.test(lastk_mediansSUS, combinedk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        gb = wilcox.test(lastk_mediansSUS, combinedk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        gc = t.test(lastk_mediansSUS, combinedk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        # 54.H0
        gd = wilcox.test(combinedk_mediansSUS, combinedk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=T);
        ge = wilcox.test(combinedk_mediansSUS, combinedk_mediansSUM, paired=F, exact=F, alternative="two.sided", correct=F);
        gf = t.test(combinedk_mediansSUS, combinedk_mediansSUM, paired=F, alternative="two.sided", var.equal=F);
        
        # Append p-values for the same k into the same line
        data = c(list(k),
                 formatP(aa["p.value"]), formatP(ab["p.value"]), formatP(ac["p.value"]),
                 formatP(ad["p.value"]), formatP(ae["p.value"]), formatP(af["p.value"]),
                 formatP(ag["p.value"]), formatP(ah["p.value"]), formatP(ai["p.value"]),
                 formatP(aj["p.value"]), formatP(ak["p.value"]), formatP(al["p.value"]),
                 formatP(am["p.value"]), formatP(an["p.value"]), formatP(ao["p.value"]),
                 formatP(ap["p.value"]), formatP(aq["p.value"]), formatP(ar["p.value"]),
                 formatP(as["p.value"]), formatP(at["p.value"]), formatP(au["p.value"]),
                 formatP(av["p.value"]), formatP(aw["p.value"]), formatP(ax["p.value"]),
                 formatP(ay["p.value"]), formatP(az["p.value"]), formatP(ba["p.value"]),
                 
                 formatP(bb["p.value"]), formatP(bc["p.value"]), formatP(bd["p.value"]),
                 formatP(be["p.value"]), formatP(bf["p.value"]), formatP(bg["p.value"]),
                 formatP(bh["p.value"]), formatP(bi["p.value"]), formatP(bj["p.value"]),
                 formatP(bk["p.value"]), formatP(bl["p.value"]), formatP(bm["p.value"]),
                 formatP(bn["p.value"]), formatP(bo["p.value"]), formatP(bp["p.value"]),
                 formatP(bq["p.value"]), formatP(br["p.value"]), formatP(bs["p.value"]),
                 formatP(bt["p.value"]), formatP(bu["p.value"]), formatP(bv["p.value"]),
                 formatP(bw["p.value"]), formatP(bx["p.value"]), formatP(by["p.value"]),
                 formatP(bz["p.value"]), formatP(ca["p.value"]), formatP(cb["p.value"]),
                 
                 formatP(cc["p.value"]), formatP(cd["p.value"]), formatP(ce["p.value"]),
                 formatP(cf["p.value"]), formatP(cg["p.value"]), formatP(ch["p.value"]),
                 formatP(ci["p.value"]), formatP(cj["p.value"]), formatP(ck["p.value"]),
                 formatP(cl["p.value"]), formatP(cm["p.value"]), formatP(cn["p.value"]),
                 formatP(co["p.value"]), formatP(cp["p.value"]), formatP(cq["p.value"]),
                 formatP(cr["p.value"]), formatP(cs["p.value"]), formatP(ct["p.value"]),
                 formatP(cu["p.value"]), formatP(cv["p.value"]), formatP(cw["p.value"]),
                 formatP(cx["p.value"]), formatP(cy["p.value"]), formatP(cz["p.value"]),
                 formatP(da["p.value"]), formatP(db["p.value"]), formatP(dc["p.value"]),
                 
                 formatP(dd["p.value"]), formatP(de["p.value"]), formatP(df["p.value"]),
                 formatP(dg["p.value"]), formatP(dh["p.value"]), formatP(di["p.value"]),
                 formatP(dj["p.value"]), formatP(dk["p.value"]), formatP(dl["p.value"]),
                 formatP(dm["p.value"]), formatP(dn["p.value"]), formatP(do["p.value"]),
                 formatP(dp["p.value"]), formatP(dq["p.value"]), formatP(dr["p.value"]),
                 formatP(ds["p.value"]), formatP(dt["p.value"]), formatP(du["p.value"]),
                 formatP(dv["p.value"]), formatP(dw["p.value"]), formatP(dx["p.value"]),
                 formatP(dy["p.value"]), formatP(dz["p.value"]), formatP(ea["p.value"]),
                 formatP(eb["p.value"]), formatP(ec["p.value"]), formatP(ed["p.value"]),
                 
                 formatP(ee["p.value"]), formatP(ef["p.value"]), formatP(eg["p.value"]),
                 formatP(eh["p.value"]), formatP(ei["p.value"]), formatP(ej["p.value"]),
                 formatP(ek["p.value"]), formatP(el["p.value"]), formatP(em["p.value"]),
                 formatP(en["p.value"]), formatP(eo["p.value"]), formatP(ep["p.value"]),
                 formatP(eq["p.value"]), formatP(er["p.value"]), formatP(es["p.value"]),
                 formatP(et["p.value"]), formatP(eu["p.value"]), formatP(ev["p.value"]),
                 formatP(ew["p.value"]), formatP(ex["p.value"]), formatP(ey["p.value"]),
                 formatP(ez["p.value"]), formatP(fa["p.value"]), formatP(fb["p.value"]),
                 formatP(fc["p.value"]), formatP(fg["p.value"]), formatP(fe["p.value"]),
                 
                 formatP(ff["p.value"]), formatP(fg["p.value"]), formatP(fh["p.value"]),
                 formatP(fi["p.value"]), formatP(fj["p.value"]), formatP(fk["p.value"]),
                 formatP(fl["p.value"]), formatP(fm["p.value"]), formatP(fn["p.value"]),
                 formatP(fo["p.value"]), formatP(fp["p.value"]), formatP(fq["p.value"]),
                 formatP(fr["p.value"]), formatP(fs["p.value"]), formatP(ft["p.value"]),
                 formatP(fu["p.value"]), formatP(fv["p.value"]), formatP(fw["p.value"]),
                 formatP(fx["p.value"]), formatP(fy["p.value"]), formatP(fz["p.value"]),
                 formatP(ga["p.value"]), formatP(gb["p.value"]), formatP(gc["p.value"]),
                 formatP(gd["p.value"]), formatP(ge["p.value"]), formatP(gf["p.value"]));
        
        write.table(data, file=out, append=T, quote=F, sep=",", col.names=F, row.names=F)
    }
}

# Read in command line parameters
# path_to_input_file, k (=max. number of tweets to consider in firstk/lastk), dst, 
# Fetch command line arguments that are sent via Python script "learning_effect_significance.py"
myArgs <- commandArgs(trailingOnly = TRUE);

# If script was passed some parameters, read the first 2 (they are identical for all cases)
if (length(myArgs) > 1)
{
    testType = myArgs[1];
    n = as.numeric(myArgs[2]);
}

######################
# For debugging only #
######################
if (length(myArgs) < 4)
{
    n=50
    # For H0 1a-1c (see learning_effect_significance.py for explanations)
    # dst = "/media/data/Workspaces/PythonWorkspace/phd/Analyze-Labeled-Dataset/infsci2017_results/stats/learning_effect/md_learning_effect_groups_in_same_institution_without_l_raw.txt"
    # s = "/media/data/Workspaces/PythonWorkspace/phd/Analyze-Labeled-Dataset/infsci2017_results/stats/learning_effect/input_md_s_learning_effect_groups_in_same_institution_without_l_raw.txt"
    # m = "/media/data/Workspaces/PythonWorkspace/phd/Analyze-Labeled-Dataset/infsci2017_results/stats/learning_effect/input_md_m_learning_effect_groups_in_same_institution_without_l_raw.txt"
    # testType = "intragroup";
    # For H0 2a-2c (see learning_effect_significance.py for explanations)
    # dst = "/media/data/Workspaces/PythonWorkspace/phd/Analyze-Labeled-Dataset/infsci2017_results/stats/learning_effect/s_learning_effect_groups_over_all_institutions_without_l_raw.txt"
    # src = "/media/data/Workspaces/PythonWorkspace/phd/Analyze-Labeled-Dataset/infsci2017_results/stats/learning_effect/input_s_learning_effect_groups_over_all_institutions_without_l_raw.txt"
    # testType = "overinstitutions";
    # For H0 3a-3c (see learning_effect_significance.py for explanations)
    dst = "/media/data/Workspaces/PythonWorkspace/phd/Analyze-Labeled-Dataset/infsci2017_results/stats/learning_effect/learning_effect_groups_in_different_institutions_without_l_raw.txt";
    mds = "/media/data/Workspaces/PythonWorkspace/phd/Analyze-Labeled-Dataset/infsci2017_results/stats/learning_effect/input_md_s_learning_effect_groups_in_same_institution_without_l_raw.txt";
    mdm = "/media/data/Workspaces/PythonWorkspace/phd/Analyze-Labeled-Dataset/infsci2017_results/stats/learning_effect/input_md_m_learning_effect_groups_in_same_institution_without_l_raw.txt";
    sus = "/media/data/Workspaces/PythonWorkspace/phd/Analyze-Labeled-Dataset/infsci2017_results/stats/learning_effect/input_su_s_learning_effect_groups_in_same_institution_without_l_raw.txt";
    sum = "/media/data/Workspaces/PythonWorkspace/phd/Analyze-Labeled-Dataset/infsci2017_results/stats/learning_effect/input_su_m_learning_effect_groups_in_same_institution_without_l_raw.txt";
    testType = "intergroup";
}

# Result for Python
result = F;

# Compute significance for groups in the same institution
if (testType == "intragroup")
{
    # Read parameters from console
    if (length(myArgs) == 5)
    {
        s = myArgs[3];
        m = myArgs[4];
        dst = myArgs[5];
    }
    
    # Append p-values to an opened file
    out = file(dst, 'w')
    
    # Load datasets
    s = loadData(s);
    m = loadData(m);
    
    # Get #tweets in S = maximum number of tweets that can be removed
    # -1 because we need at least 1 different tweet in lastk and firstk, otherwise
    # significance tests return NaN (as firstk = lastk)
    maxk = ncol(s) - 1;
    
    # Extract <GROUP> and <INSTITUTION> from file name
    # fName = basename(src);
    # institution = strsplit(fName, "_")[[1]][[2]]
    # group = strsplit(fName, "_")[[1]][[3]]
    
    # Create header of file and write it to file
    header = 
"M = 1-sample Mann-Whitney U;W = 1-sample Wilcoxon signed rank test; T = 1-sample unpaired t-test(Baum-Welch)
M2 = 2-sample Mann-Whitney U; W2 = 2-sample Wilcoxon-Mann-Whitney rank sum test; T2 = 2-sample unpaired t-test(Baum-Welch) 
1.H0: there is no difference in the firstK tweets among the annotators of <GROUP> in <INSTITUTION>.
2.H0: there is no difference in the lastK tweets among the annotators of <GROUP> in <INSTITUTION>.
3.H0: there is no difference in the firstk+lastK tweets among the annotators of <GROUP> in <INSTITUTION>.
4.H0: there is no difference in the set of the  median annotation times of the firstk tweets compared with the set of the  lastk median annotation times in tweets of <GROUP> in <INSTITUTION>.
5.H0: there is no difference in the set of the  median annotation times of the firstk tweets compared with the set of the  firstk+lastk median annotation times in tweets of <GROUP> in <INSTITUTION>.
6.H0: there is no difference in the set of the  median annotation times of the lastk tweets compared with the set of the  firstk+lastk median annotation times in tweets of <GROUP> in <INSTITUTION>. 
group k 1.H0(M) 1.H0(W) 1.H0(T) 2.H0(M) 2.H0(W) 2.H0(T) 3.H0(M) 3.H0(W) 3.H0(T) 4.H0(M2) 4.H0(W2) 4.H0(T2) 5.H0(M2) 5.H0(W2) 5.H0(T2) 6.H0(M2) 6.H0(W2) 6.H0(T2)
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++";
    # pre = paste(toupper(institution), toupper(group), "\n-------\n",sep=" ")
    # header = paste(pre, header, sep="")
    writeLines(header, con=out);
    # If there are more than 1 annotator per dataset
    if (nrow(s) > 1 && nrow(m) > 1)
    {
        intraGroupSignificance(s, m, out, min(n, maxk));
    }
    else
    {
        writeLines("Too few annotators (<=1) in 1 dataset, so no test is possible", con=out)
    }
} else if (testType == "overinstitutions")
{
    # Read parameters from console
    if (length(myArgs) == 4)
    {
        src = myArgs[3];
        dst = myArgs[4];
    }
    # Append p-values to an opened file
    out = file(dst, 'w')
    
    myData = loadData(src);
    
    # Get #tweets in S = maximum number of tweets that can be removed
    # -1 because we need at least 1 different tweet in lastk and firstk, otherwise
    # significance tests return NaN (as firstk = lastk)
    maxk = ncol(myData) - 1;
    
    # Extract <GROUP> and <INSTITUTION> from file name
    fName = basename(src);
    institution = "SU+MD"
    group = strsplit(fName, "_")[[1]][[2]]
    
    # Create header of file and write it to file
    header = 
"M = 1-sample Mann-Whitney U;W = 1-sample Wilcoxon signed rank test; T = 1-sample unpaired t-test(Baum-Welch)
M2 = 2-sample Mann-Whitney U; W2 = 2-sample Wilcoxon-Mann-Whitney rank sum test; T2 = 2-sample unpaired t-test(Baum-Welch) 
Using MD and SU together and compare the groups:
1.H0: there is no difference in the firstK tweets among the annotators in <GROUP>.
2.H0: there is no difference in the lastK tweets among the annotators in <GROUP>.
3.H0: there is no difference between the set of firstK tweets and the set of the lastK tweets in <GROUP>.
4.H0: there is no difference in the set of the  median annotation times of the firstk tweets compared with the set of the  lastk median annotation times in tweets.
5.H0: there is no difference in the set of the median annotation times of the firstk tweets compared with the set of the  firstk+lastk median annotation times in tweets.
6.H0: there is no difference in the set of the median annotation times of the lastk tweets compared with the set of the firstk+lastk median annotation times in tweets. 
k 1.H0(M) 1.H0(W) 1.H0(T) 2.H0(M) 2.H0(W) 2.H0(T) 3.H0(M) 3.H0(W) 3.H0(T) 4.H0(M2) 4.H0(W2) 4.H0(T2) 5.H0(M2) 5.H0(W2) 5.H0(T2) 6.H0(M2) 6.H0(W2) 6.H0(T2)
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++";
    pre = paste(institution, toupper(group), "\n----------\n",sep=" ")
    header = paste(pre, header, sep="")
    writeLines(header, con=out);
    if (nrow(myData) > 1)
    {
        interGroupSignificance(myData, out, min(n, maxk));
    }
    else
    {
        writeLines("Too few annotators (<=1), so no test is possible", con=out)
    }
} else if (testType == "intergroup")
{
    # Read parameters from console
    if (length(myArgs) == 7)
    {
        mds = myArgs[3];
        mdm = myArgs[4];
        sus = myArgs[5];
        sum = myArgs[6];
        dst = myArgs[7];
    }
    # Append p-values to an opened file
    out = file(dst, 'w')
    
    mds = loadData(mds);
    mdm = loadData(mdm);
    sus = loadData(sus);
    sum = loadData(sum);
    
    # Extract <GROUP> and <INSTITUTION> from file name
    # fName = basename(src);
    # institution = strsplit(fName, "_")[[1]][[2]]
    # group = strsplit(fName, "_")[[1]][[3]]
    
    # Get #tweets in S = maximum number of tweets that can be removed
    # -1 because we need at least 1 different tweet in lastk and firstk, otherwise
    # significance tests return NaN (as firstk = lastk)
    maxk1 = ncol(mds) - 1;
    maxk2 = ncol(sus) - 1;
    
    # Create header of file and write it to file
    header = 
"M2 = 2-sample Mann-Whitney U; W2 = 2-sample Wilcoxon-Mann-Whitney rank sum test; T2 = 2-sample unpaired t-test(Baum-Welch) 
Unpaired because we shuffled firstk and lastk to avoid having to control the order of the tweets, which means a loss in power of the test, but if infsci2017_results are still significant, they'll also be significant with paired test
# MD S vs. SU S
1.H0: there is no difference in the set of firstK tweets among the annotators of S in SU and MD.
2.H0: there is no difference in the set of firstK tweets among the annotators of S in SU and the set of lastK tweets in MD in S.
3.H0: there is no difference in the set of firstK tweets among the annotators of S in SU and the set of firstK+lastK tweets in MD in S.
4.H0: there is no difference in the set of lastK tweets among the annotators of S in SU and the set of firstK tweets in MD in S.
5.H0: there is no difference in the set of lastK tweets among the annotators of S in SU and MD.
6.H0: there is no difference in the set of lastK tweets among the annotators of S in SU and the set of firstK+lastK tweets in MD in S.
7.H0: there is no difference in the set of firstk+lastK tweets among the annotators of S in SU and the set of firstK tweets in MD in S.
8.H0: there is no difference in the set of firstk+lastK tweets among the annotators of S in SU and the set of lastK tweets in MD in S.
9.H0: there is no difference in the set of firstk+lastK tweets among the annotators of S in SU and MD.
# MD M vs. SU M
10.H0: there is no difference in the set of firstK tweets among the annotators of M in SU and MD.
11.H0: there is no difference in the set of firstK tweets among the annotators of M in SU and the set of lastK tweets in MD in M.
12.H0: there is no difference in the set of firstK tweets among the annotators of M in SU and the set of firstK+lastK tweets in MD in M.
13.H0: there is no difference in the set of lastK tweets among the annotators of M in SU and the set of firstK tweets in MD in M.
14.H0: there is no difference in the set of lastK tweets among the annotators of M in SU and MD.
15.H0: there is no difference in the set of lastK tweets among the annotators of M in SU and the set of firstK+lastK tweets in MD in M.
16.H0: there is no difference in the set of firstk+lastK tweets among the annotators of M in SU and the set of firstK tweets in MD in M.
17.H0: there is no difference in the set of firstk+lastK tweets among the annotators of M in SU and the set of lastK tweets in MD in M.
18.H0: there is no difference in the set of firstk+lastK tweets among the annotators of M in SU and MD.
# MD S vs. SU M
19.H0: there is no difference in the set of firstK tweets of S in MD compared with the set of firstK tweets of the annotators of M in SU.
20.H0: there is no difference in the set of firstK tweets of S in MD compared with the set of lastK tweets of the annotators of M in SU.
21.H0: there is no difference in the set of firstK tweets of S in MD compared with the set of firstK+lastK tweets of the annotators of M in SU.
22.H0: there is no difference in the set of lastK tweets of S in MD compared with the set of firstK tweets of the annotators of M in SU.
23.H0: there is no difference in the set of lastK tweets of S in MD compared with the set of lastK tweets of the annotators of M in SU.
24.H0: there is no difference in the set of lastK tweets of S in MD compared with the set of firstK+lastK tweets of the annotators of M in SU.
25.H0: there is no difference in the set of firstK+lastK tweets of S in MD compared with the set of firstk tweets of the annotators of M in SU.
26.H0: there is no difference in the set of firstK+lastK tweets of S in MD compared with the set of lastK tweets of the annotators of M in SU.
27.H0: there is no difference in the set of firstK+lastK tweets of S in MD compared with the set of firstk+lastK tweets of the annotators of M in SU.
# MD M vs. SU S
28.H0: there is no difference in the set of firstK tweets of M in MD compared with the set of firstK tweets of the annotators of S in SU.
29.H0: there is no difference in the set of firstK tweets of M in MD compared with the set of lastK tweets of the annotators of S in SU.
30.H0: there is no difference in the set of firstK tweets of M in MD compared with the set of firstK+lastK tweets of the annotators of S in SU.
31.H0: there is no difference in the set of lastK tweets of M in MD compared with the set of firstK tweets of the annotators of S in SU.
32.H0: there is no difference in the set of lastK tweets of M in MD compared with the set of lastK tweets of the annotators of S in SU.
33.H0: there is no difference in the set of lastK tweets of M in MD compared with the set of firstK+lastK tweets of the annotators of S in SU.
34.H0: there is no difference in the set of firstK+lastK tweets of M in MD compared with the set of firstk tweets of the annotators of S in SU.
35.H0: there is no difference in the set of firstK+lastK tweets of M in MD compared with the set of lastK tweets of the annotators of S in SU.
36.H0: there is no difference in the set of firstK+lastK tweets of M in MD compared with the set of firstk+lastK tweets of the annotators of S in SU.
# MD S vs. MD M
37.H0: there is no difference in the set of firstK tweets of M in MD compared with the set of firstK tweets of the annotators of S in MD.
38.H0: there is no difference in the set of firstK tweets of M in MD compared with the set of lastK tweets of the annotators of S in MD.
39.H0: there is no difference in the set of firstK tweets of M in MD compared with the set of firstK+lastK tweets of the annotators of S in MD.
40.H0: there is no difference in the set of lastK tweets of M in MD compared with the set of firstK tweets of the annotators of S in MD.
41.H0: there is no difference in the set of lastK tweets of M in MD compared with the set of lastK tweets of the annotators of S in MD.
42.H0: there is no difference in the set of lastK tweets of M in MD compared with the set of firstK+lastK tweets of the annotators of S in MD.
43.H0: there is no difference in the set of firstK+lastK tweets of M in MD compared with the set of firstk tweets of the annotators of S in MD.
44.H0: there is no difference in the set of firstK+lastK tweets of M in MD compared with the set of lastK tweets of the annotators of S in MD.
45.H0: there is no difference in the set of firstK+lastK tweets of M in MD compared with the set of firstk+lastK tweets of the annotators of S in MD.
# SU S vs. SU M
46.H0: there is no difference in the set of firstK tweets of M in SU compared with the set of firstK tweets of the annotators of S in SU.
47.H0: there is no difference in the set of firstK tweets of M in SU compared with the set of lastK tweets of the annotators of S in SU.
48.H0: there is no difference in the set of firstK tweets of M in SU compared with the set of firstK+lastK tweets of the annotators of S in SU.
49.H0: there is no difference in the set of lastK tweets of M in SU compared with the set of firstK tweets of the annotators of S in SU.
50.H0: there is no difference in the set of lastK tweets of M in SU compared with the set of lastK tweets of the annotators of S in SU.
51.H0: there is no difference in the set of lastK tweets of M in SU compared with the set of firstK+lastK tweets of the annotators of S in SU.
52.H0: there is no difference in the set of firstK+lastK tweets of M in SU compared with the set of firstk tweets of the annotators of S in SU.
53.H0: there is no difference in the set of firstK+lastK tweets of M in SU compared with the set of lastK tweets of the annotators of S in SU.
54.H0: there is no difference in the set of firstK+lastK tweets of M in SU compared with the set of firstk+lastK tweets of the annotators of S in SU.

k 1.H0(M2) 1.H0(W2) 1.H0(T2) 2.H0(M2) 2.H0(W2) 2.H0(T2) 3.H0(M2) 3.H0(W2) 3.H0(T2) 4.H0(M2) 4.H0(W2) 4.H0(T2) 5.H0(M2) 5.H0(W2) 5.H0(T2) 6.H0(M2) 6.H0(W2) 6.H0(T2) 7.H0(M2) 7.H0(W2) 7.H0(T2) 8.H0(M2) 8.H0(W2) 8.H0(T2) 9.H0(M2) 9.H0(W2) 9.H0(T2) 10.H0(M2) 10.H0(W2) 10.H0(T2) 11.H0(M2) 11.H0(W2) 11.H0(T2) 12.H0(M2) 12.H0(W2) 12.H0(T2) 13.H0(M2) 13.H0(W2) 13.H0(T2) 14.H0(M2) 14.H0(W2) 14.H0(T2) 15.H0(M2) 15.H0(W2) 15.H0(T2) 16.H0(M2) 16.H0(W2) 16.H0(T2) 17.H0(M2) 17.H0(W2) 17.H0(T2) 18.H0(M2) 18.H0(W2) 18.H0(T2) 19.H0(M2) 19.H0(W2) 19.H0(T2) 20.H0(M2) 20.H0(W2) 20.H0(T2) 21.H0(M2) 21.H0(W2) 21.H0(T2) 22.H0(M2) 22.H0(W2) 22.H0(T2) 23.H0(M2) 23.H0(W2) 23.H0(T2) 24.H0(M2) 24.H0(W2) 24.H0(T2) 25.H0(M2) 25.H0(W2) 25.H0(T2) 26.H0(M2) 26.H0(W2) 26.H0(T2) 27.H0(M2) 27.H0(W2) 27.H0(T2) 28.H0(M2) 28.H0(W2) 28.H0(T2) 29.H0(M2) 29.H0(W2) 29.H0(T2) 30.H0(M2) 30.H0(W2) 30.H0(T2) 31.H0(M2) 31.H0(W2) 31.H0(T2) 32.H0(M2) 32.H0(W2) 32.H0(T2) 33.H0(M2) 33.H0(W2) 33.H0(T2) 34.H0(M2) 34.H0(W2) 34.H0(T2) 35.H0(M2) 35.H0(W2) 35.H0(T2) 36.H0(M2) 36.H0(W2) 36.H0(T2) 37.H0(M2) 37.H0(W2) 37.H0(T2) 38.H0(M2) 38.H0(W2) 38.H0(T2) 39.H0(M2) 39.H0(W2) 39.H0(T2) 40.H0(M2) 40.H0(W2) 40.H0(T2) 41.H0(M2) 41.H0(W2) 41.H0(T2) 42.H0(M2) 42.H0(W2) 42.H0(T2) 43.H0(M2) 43.H0(W2) 43.H0(T2) 44.H0(M2) 44.H0(W2) 44.H0(T2) 45.H0(M2) 45.H0(W2) 45.H0(T2) 46.H0(M2) 46.H0(W2) 46.H0(T2) 47.H0(M2) 47.H0(W2) 47.H0(T2) 48.H0(M2) 48.H0(W2) 48.H0(T2) 49.H0(M2) 49.H0(W2) 49.H0(T2) 50.H0(M2) 50.H0(W2) 50.H0(T2) 51.H0(M2) 51.H0(W2) 51.H0(T2) 52.H0(M2) 52.H0(W2) 52.H0(T2) 53.H0(M2) 53.H0(W2) 53.H0(T2) 54.H0(M2) 54.H0(W2) 54.H0(T2) 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++";
    # pre = paste(toupper(institution), toupper(group), "\n-------\n",sep=" ")
    # header = paste(pre, header, sep="")
    writeLines(header, con=out);
    # > 1 annotator per dataset
    if (nrow(sus) > 1 && nrow(sum) > 1 && nrow(mds) > 1 && nrow(mdm) > 1)
    {
        interInstGroupSignificance(mds, mdm, sus, sum, out, min(n, maxk1, maxk2));
    }
    else
    {
        writeLines("Too few annotators (<=1) in at least 1 dataset, so no test is possible", con=out)
    }
}
close(out);
result = T;
cat(result);